let items = [{
        name: "Gold",
        img: "images/icons/clay.png",
        type: "Currency",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: true,
        storePrice: null,
        weight: 0,
    },
    {
        name: "Clay",
        img: "images/icons/clay.png",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 1,
        weight: 1,
    },
    {
        name: "Copper Ore",
        img: "images/icons/copperOre.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        name: "Tin Ore",
        img: "images/icons/tinOre.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        name: "Rune Essence",
        img: "images/icons/runeEssence.png",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 0.002,
    },
    {
        name: "Blurite Ore",
        img: "images/icons/bluriteOre.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        name: "Limestone",
        img: "images/icons/limestone.png",
        type: "Material",
        members: true,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 2.267,
    },
    {
        name: "Iron Ore",
        img: "images/icons/ironOre.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 25,
        weight: 2.267,
    },
    {
        name: "Silver Ore",
        img: "images/icons/silverOre.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 112,
        weight: 2.267,
    },
    {
        name: "Elemental Ore",
        img: "images/icons/elementalOre.png",
        type: "Ore",
        members: true,
        tradeable: false,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        name: "Pure Essence",
        img: "images/icons/pureEssence.png",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 100,
        weight: 0.002,
    },
    {
        name: "Coal",
        img: "images/icons/coal.png",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 67,
        weight: 2.267,
    },
];