let items = [{
        name: "Gold",
        type: "Currency",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: true,
        storePrice: null,
        weight: 0,
    },
    {
        name: "Clay",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 1,
        weight: 1,
    },
    {
        name: "Copper Ore",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        name: "Tin Ore",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        name: "Rune Essence",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 0.002,
    },
    {
        name: "Blurite Ore",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        name: "Limestone",
        type: "Material",
        members: true,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 2.267,
    },
    {
        name: "Iron Ore",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 25,
        weight: 2.267,
    },
    {
        name: "Silver Ore",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 112,
        weight: 2.267,
    },
    {
        name: "Elemental Ore",
        type: "Ore",
        members: true,
        tradeable: false,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        name: "Pure Essence",
        type: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 100,
        weight: 0.002,
    },
    {
        name: "Coal",
        type: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 67,
        weight: 2.267,
    },
];