let items = [
    {
        id: 0,
        name: "Gold",
        itemType: "Currency",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: true,
        storePrice: null,
        weight: 0,
    },
    {
        id: 1,
        name: "Clay",
        itemType: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 1,
        weight: 1,
    },
    {
        id: 2,
        name: "Copper Ore",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        id: 3,
        name: "Tin Ore",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 4,
        weight: 2.267,
    },
    {
        id: 4,
        name: "Rune Essence",
        itemType: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 0.002,
    },
    {
        id: 5,
        name: "Blurite Ore",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        id: 6,
        name: "Limestone",
        itemType: "Material",
        members: true,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 10,
        weight: 2.267,
    },
    {
        id: 7,
        name: "Iron Ore",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 25,
        weight: 2.267,
    },
    {
        id: 8,
        name: "Silver Ore",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 112,
        weight: 2.267,
    },
    {
        id: 9,
        name: "Elemental Ore",
        itemType: "Ore",
        members: true,
        tradeable: false,
        equipable: false,
        stackable: false,
        storePrice: null,
        weight: 2.267,
    },
    {
        id: 10,
        name: "Pure Essence",
        itemType: "Material",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 100,
        weight: 0.002,
    },
    {
        id: 11,
        name: "Coal",
        itemType: "Ore",
        members: false,
        tradeable: true,
        equipable: false,
        stackable: false,
        storePrice: 67,
        weight: 2.267,
    },
];