let player = {
    combatLevel: 3,
    exp: 0,
    levelExp: 0,
    skills: [],
    equipment: [],
    inventory: [],
    bank: [],
    skills: {
        attack: {level: 1, exp: 0, levelExp: 0},
        hitpoints: {level: 1, exp: 0, levelExp: 0},
        mining: {level: 1, exp: 0, levelExp: 0},
        strength: {level: 1, exp: 0, levelExp: 0},
        agility: {level: 1, exp: 0, levelExp: 0},
        smithing: {level: 1, exp: 0, levelExp: 0},
        defence: {level: 1, exp: 0, levelExp: 0},
        herblore: {level: 1, exp: 0, levelExp: 0},
        fishing: {level: 1, exp: 0, levelExp: 0},
        ranged: {level: 1, exp: 0, levelExp: 0},
        thieving: {level: 1, exp: 0, levelExp: 0},
        cooking: {level: 1, exp: 0, levelExp: 0},
        prayer: {level: 1, exp: 0, levelExp: 0},
        crafting: {level: 1, exp: 0, levelExp: 0},
        firemaking: {level: 1, exp: 0, levelExp: 0},
        magic: {level: 1, exp: 0, levelExp: 0},
        fletching: {level: 1, exp: 0, levelExp: 0},
        woodcutting: {level: 1, exp: 0, levelExp: 0},
        runecrafting: {level: 1, exp: 0, levelExp: 0},
        slayer: {level: 1, exp: 0, levelExp: 0},
        farming: {level: 1, exp: 0, levelExp: 0},
        construction: {level: 1, exp: 0, levelExp: 0},
        hunter: {level: 1, exp: 0, levelExp: 0},
    },
}